import Head from 'next/head'
import { Button ,Grid,Col} from '@mantine/core'
import Form from '../components/Form'
import OrderBook from '../components/OrderBook'
import UserPortFolio from '../components/UserPortFolio'
import Transactions from '../components/Transactions'
import Graph from '../components/Graph'
import PlotlyGraph from '../components/PlotlyGraph'



export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid className="h-screen">
          <Col span={6}>
            <Transactions />
          </Col>
          <Col span={6}>
            <Transactions />
          </Col>
          <Col span={6} className="flex justify-center h-2/5">
            <Graph />
          </Col>

          <Col span={6} className="flex justify-center h-2/5">
            <OrderBook />
          </Col>
          <Col span={6} className="flex justify-center h-2/5">
            <UserPortFolio />
          </Col>
          <Col span={6} className="flex justify-center h-2/5">
            <Form></Form>
          </Col>
        </Grid>
      </main>
    </div>
  );
}
