import Head from 'next/head'
import { Button ,Grid,Col} from '@mantine/core'
import Form from '../components/Form'
import OrderBook from '../components/OrderBook'
import UserPortFolio from '../components/UserPortFolio'
import Transactions from '../components/Transactions'
import Graph from '../components/Graph'
import { useSelector, useDispatch } from 'react-redux'
import PlotlyGraph from '../components/PlotlyGraph'
import { setData } from '../store/appDataSlice'
import { useEffect } from 'react'
import NavBar from '../components/NavBar'
import axios from 'axios'
import  { IoNotificationsSharp as NotificationIcon } from 'react-icons/io5'
import { useState } from 'react'

export default function Home() {

  const appData = useSelector((state) => state.appData)
  const dispatch = useDispatch()

  const [error, setError] = useState(false)
  
  const setDataInStore = (data) => {
    // set the data
    console.log('Setting data')
    console.log(data)
    dispatch(() => setData(data))
  }

  useEffect(() => {
    console.log('use effect')
    axios
      .get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/get-all-data`)
      .then(res => setData(res.data))
  }, [])
  console.log("njk")
  console.log(appData)
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen'>
        
        {/* <NavBar /> */}

        <Grid className="">
          {/* <Col span={6}>
            
          </Col>
          <Col span={3} className="flex justify-end mt-4">

          <Transactions name="Transactions" />
          </Col>
          <Col span={3} className="flex justify-start mt-4">

            <Transactions name="Notifications" />
          </Col> */}
          <Col span={6} className="flex justify-end h-2/5">
            <Graph />
          </Col>

          <Col span={6} className="flex justify-start h-2/5">
            <OrderBook />
          </Col>
          <Col span={6} className="flex justify-end h-2/5">
            <UserPortFolio />
          </Col>
          <Col span={6} className="flex justify-start h-2/5">
            <Form></Form>
          </Col>
        </Grid>
      </main>
    </div>
  );
}
